In [1]:
! pip3 install numpy



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\Miras\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
a.ndim # dimention of the array
a.shape # no. rows and no. of column

(4,)

In [15]:
# return me string chaiy to dtype use karenge
a=np.array([1,2,3,4],dtype=str)
a,


(array(['1', '2', '3', '4'], dtype='<U1'),)

In [ ]:
# two dimentional array
b=np.array([[1,2,3,4],[5,6,7,8]])
b.shape


2

In [10]:
b.ndim

2

In [14]:
# three dimentional array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c,

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),)

In [ ]:
x=np.linspace(1,12)

array([ 1.        ,  1.2244898 ,  1.44897959,  1.67346939,  1.89795918,
        2.12244898,  2.34693878,  2.57142857,  2.79591837,  3.02040816,
        3.24489796,  3.46938776,  3.69387755,  3.91836735,  4.14285714,
        4.36734694,  4.59183673,  4.81632653,  5.04081633,  5.26530612,
        5.48979592,  5.71428571,  5.93877551,  6.16326531,  6.3877551 ,
        6.6122449 ,  6.83673469,  7.06122449,  7.28571429,  7.51020408,
        7.73469388,  7.95918367,  8.18367347,  8.40816327,  8.63265306,
        8.85714286,  9.08163265,  9.30612245,  9.53061224,  9.75510204,
        9.97959184, 10.20408163, 10.42857143, 10.65306122, 10.87755102,
       11.10204082, 11.32653061, 11.55102041, 11.7755102 , 12.        ])

In [23]:
y=np.linspace(1,100,num=30,dtype=int)

In [ ]:
y.reshape(5,6) # used to reshape the current into the matrix 
#0r
m=np.linspace(1,8,num=12,dtype=int).reshape(4,3) # direct 2d formation in the form of matrix
m,

(array([[1, 1, 2],
        [2, 3, 4],
        [4, 5, 6],
        [6, 7, 8]]),)

create a 2d arry and find shape size and dimention

In [31]:
x=np.array([[1,2,3],[4,5,6]])
x,
print(x.shape)
print(x.ndim)


(2, 3)
2


create 3d array 

In [34]:
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x,

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),)

create numpy array with values from 1 to 16 and reshap in the 4X4 matrix by using np.arange and np.reshap 

In [36]:
x=np.arange(1,17).reshape(4,4)
x,

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),)

matrixs operation

eigon vector :
the direction for the movement of a specific vactor is known by eigon vactor 

In [2]:
import numpy as np

In [22]:
x=np.linspace(1,25,num=25,dtype=int).reshape(5,5)# bidefult ye float element leta h isily hm dtype= keyword ka use karte hai 
x,

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),)

In [12]:
# rank of the matrix
#keyword= matrix_rank()
np.linalg.matrix_rank(x)

np.int64(2)

In [13]:
#eigon value
#keyword= eigvals()
np.linalg.eigvals(x)


array([ 6.86420807e+01+0.00000000e+00j, -3.64208074e+00+0.00000000e+00j,
       -2.90915693e-15+2.38171334e-15j, -2.90915693e-15-2.38171334e-15j,
        1.97408863e-16+0.00000000e+00j])

In [14]:
# if we use eig() keywords then we will get both eigon value and eigon vector at same time 
np.linalg.eig(x)


EigResult(eigenvalues=array([ 6.86420807e+01+0.00000000e+00j, -3.64208074e+00+0.00000000e+00j,
       -2.90915693e-15+2.38171334e-15j, -2.90915693e-15-2.38171334e-15j,
        1.97408863e-16+0.00000000e+00j]), eigenvectors=array([[-0.10797496+0.j        ,  0.67495283+0.j        ,
         0.14670174+0.1909791j ,  0.14670174-0.1909791j ,
        -0.07390125+0.j        ],
       [-0.25277499+0.j        ,  0.3603897 +0.j        ,
         0.3294084 -0.26685261j,  0.3294084 +0.26685261j,
        -0.19697337+0.j        ],
       [-0.39757502+0.j        ,  0.04582657+0.j        ,
        -0.59267376+0.j        , -0.59267376-0.j        ,
         0.74972491+0.j        ],
       [-0.54237506+0.j        , -0.26873656+0.j        ,
        -0.38968465+0.03664144j, -0.38968465-0.03664144j,
        -0.61292471+0.j        ],
       [-0.68717509+0.j        , -0.58329969+0.j        ,
         0.50624827+0.03923207j,  0.50624827-0.03923207j,
         0.13407442+0.j        ]]))

In [20]:
#if we want eigon value and vector seprate so that we have to store both of them 
eigon_value, eigon_vactor = np.linalg.eig(x)
# eigon_vactor
eigon_value

array([ 6.86420807e+01+0.00000000e+00j, -3.64208074e+00+0.00000000e+00j,
       -2.90915693e-15+2.38171334e-15j, -2.90915693e-15-2.38171334e-15j,
        1.97408863e-16+0.00000000e+00j])

In [23]:
# diterminant : measures the scaling factor and to find the rotations and shareing we use diterminant
np.linalg.det(x)

np.float64(0.0)

In [24]:
# invers 
np.linalg.inv(x) # inverse will not determine due to the det of x is 00


LinAlgError: Singular matrix

In [25]:
# transpose 
np.linalg.matrix_transpose(x)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

make a matrix 

In [52]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[0,9,8],[7,6,5],[4,3,2]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 9 8]
 [7 6 5]
 [4 3 2]]


In [33]:
np.dot(a,b) # dot product of the given two matrix

array([[ 26,  30,  24],
       [ 59,  84,  69],
       [ 92, 138, 114]])

In [34]:
np.cross(a,b) # cross product of the given two matrix

array([[-11,  -8,   9],
       [-11,  22, -11],
       [-11,  22, -11]])

In [49]:
np.add(a,b) # addition of given two matrix

array([[ 1, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [ ]:
r=np.diagonal(a)
s=np.diagonal(b)

array([0, 6, 2])

In [54]:
# vstack() is used for stack in vertically 
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 9, 8],
       [7, 6, 5],
       [4, 3, 2]])

In [55]:
# hstack() is used for stack in horizontally 
np.hstack([a,b])

array([[1, 2, 3, 0, 9, 8],
       [4, 5, 6, 7, 6, 5],
       [7, 8, 9, 4, 3, 2]])

In [58]:
# we can perfom all the matematic calculation which  could be applied on matix
#addition of element in a matrix
print(a+6)
#multiplication of element in a matrix
print(a*6)
#substraction of element in a matrix
print(a-6)
#division of element in a matrix
print(a/6)
#dot multiplication of two mateix 
print(a*b)


[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 6 12 18]
 [24 30 36]
 [42 48 54]]
[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[[0.16666667 0.33333333 0.5       ]
 [0.66666667 0.83333333 1.        ]
 [1.16666667 1.33333333 1.5       ]]
[[ 0 18 24]
 [28 30 30]
 [28 24 18]]


create a 6x6 matrix by using arange() function and find eigon value ,eigon vactor, rank , determenant and diagonal of the elements

In [45]:
ele= np.arange(1,37,dtype=int).reshape(6,6)
ele

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [47]:
eigon_vactor_ele, eigon_value_ele =np.linalg.eig(ele)
print('eigon vactor =',eigon_vactor_ele)
print()
print('eigon value =',eigon_value_ele)
print()
rank=np.linalg.matrix_rank(ele)
print('rank =',rank)
print()
determinant= np.linalg.det(ele)
print('determinant =',determinant)
print()
diag=np.linalg.diagonal(ele)
print('diagonal =',diag)

eigon vactor = [ 1.16411822e+02+0.00000000e+00j -5.41182151e+00+0.00000000e+00j
 -1.29522752e-15+3.03403945e-15j -1.29522752e-15-3.03403945e-15j
 -3.36522484e-15+0.00000000e+00j  1.73182808e-15+0.00000000e+00j]

eigon value = [[-0.08190341+0.j          0.63110943+0.j         -0.22481244+0.23752107j
  -0.22481244-0.23752107j  0.32514027+0.j          0.02966602+0.j        ]
 [-0.19353989+0.j          0.39298443+0.j          0.68634984+0.j
   0.68634984-0.j         -0.62687855+0.j          0.28386664+0.j        ]
 [-0.30517638+0.j          0.15485944+0.j         -0.35278768-0.40954769j
  -0.35278768+0.40954769j  0.56403408+0.j         -0.45282174+0.j        ]
 [-0.41681286+0.j         -0.08326555+0.j         -0.2747546 -0.03214635j
  -0.2747546 +0.03214635j -0.40243915+0.j         -0.32864799+0.j        ]
 [-0.52844934+0.j         -0.32139055+0.j         -0.01346493+0.1053304j
  -0.01346493-0.1053304j  -0.0054111 +0.j          0.73196456+0.j        ]
 [-0.64008582+0.j         -0.55951554+

TypeError: vstack() takes 1 positional argument but 2 were given

In [1]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,3])
x=a+b
print(x)

NameError: name 'np' is not defined

In [ ]:
#broadcasting : set of rule for aline array with different shape so that they can be use for operation, 
# it allow us to perform operations on array with diffrent no. of diration or different sizes in one or more dimentions
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,3])
x=a+b
print(x)

[[2 4 6]
 [5 7 9]]


pandas : to do : data cleaning, data visualisation, data mining, data wrangling
        features: series: one dimentional 
            data frame : 2 dimentional
            panal : 3 dimentional 

In [ ]:
# series: it is the one dimentional labeled array of the values that can be use to represent a column of data in a data frame
